"use client";
import {useEffect,useRef,useState} from "react";
type Stone=0|1|2;const N=15,S=520,P=28,C=(S-P*2)/(N-1);const empty=()=>Array.from({length:N},()=>Array<Stone>(N).fill(0));
function win(b:Stone[][],r:number,c:number,s:Stone){for(const [dr,dc] of [[1,0],[0,1],[1,1],[1,-1]]){let n=1;for(const q of [1,-1]){let rr=r+dr*q,cc=c+dc*q;while(rr>=0&&rr<N&&cc>=0&&cc<N&&b[rr][cc]===s){n++;rr+=dr*q;cc+=dc*q}}if(n>=5)return true}return false}
function ai(b:Stone[][]){let best:[number,number]|null=null,score=-1;for(let r=0;r<N;r++)for(let c=0;c<N;c++)if(!b[r][c]){let s=0;for(let dr=-2;dr<=2;dr++)for(let dc=-2;dc<=2;dc++){const rr=r+dr,cc=c+dc;if(rr>=0&&rr<N&&cc>=0&&cc<N&&b[rr][cc])s+=6-Math.max(Math.abs(dr),Math.abs(dc))}const x=b.map(v=>v.slice()) as Stone[][];x[r][c]=2;if(win(x,r,c,2))s+=100000;x[r][c]=1;if(win(x,r,c,1))s+=90000;if(s>score){score=s;best=[r,c]}}return best}
export default function Omok(){const cv=useRef<HTMLCanvasElement>(null);const [b,setB]=useState<Stone[][]>(empty);const [turn,setTurn]=useState<Stone>(1);const [mode,setMode]=useState<"ai"|"2p">("ai");const [msg,setMsg]=useState("흑 차례");const [done,setDone]=useState(false);
useEffect(()=>{const x=cv.current;if(!x)return;const g=x.getContext("2d")!;g.clearRect(0,0,S,S);g.fillStyle="#dcae67";g.fillRect(0,0,S,S);g.strokeStyle="#5b4020";for(let i=0;i<N;i++){const p=P+i*C;g.beginPath();g.moveTo(P,p);g.lineTo(S-P,p);g.stroke();g.beginPath();g.moveTo(p,P);g.lineTo(p,S-P);g.stroke()}b.forEach((row,r)=>row.forEach((v,c)=>{if(!v)return;g.beginPath();g.arc(P+c*C,P+r*C,14,0,Math.PI*2);g.fillStyle=v===1?"#111":"#fafafa";g.fill();g.stroke()}))},[b]);
function put(r:number,c:number,s:Stone){if(done||b[r][c])return;const n=b.map(v=>v.slice()) as Stone[][];n[r][c]=s;setB(n);if(win(n,r,c,s)){setDone(true);setMsg(s===1?"흑 승리!":"백 승리!");return}const next=s===1?2:1;setTurn(next);setMsg(next===1?"흑 차례":"백 차례");if(mode==="ai"&&s===1){setTimeout(()=>{const q=ai(n);if(q){const [ar,ac]=q;const m=n.map(v=>v.slice()) as Stone[][];m[ar][ac]=2;setB(m);if(win(m,ar,ac,2)){setDone(true);setMsg("컴퓨터 승리!")}else{setTurn(1);setMsg("흑 차례")}}},180)}}
return <div className="game"><h1>오목</h1><p>15×15 자유 오목 · 5개 이상 연속 시 승리</p><div className="controls"><button onClick={()=>{setMode("ai");setB(empty());setTurn(1);setDone(false);setMsg("흑 차례")}} className={mode==="ai"?"on":""}>컴퓨터 대전</button><button onClick={()=>{setMode("2p");setB(empty());setTurn(1);setDone(false);setMsg("흑 차례")}} className={mode==="2p"?"on":""}>같은 기기 2인용</button><button onClick={()=>{setB(empty());setTurn(1);setDone(false);setMsg("흑 차례")}}>다시 시작</button></div><strong className="status">{msg}</strong><canvas ref={cv} width={S} height={S} onClick={e=>{const rect=e.currentTarget.getBoundingClientRect();const c=Math.round(((e.clientX-rect.left)*S/rect.width-P)/C),r=Math.round(((e.clientY-rect.top)*S/rect.height-P)/C);if(r>=0&&r<N&&c>=0&&c<N&&(mode==="2p"||turn===1))put(r,c,turn)}}/><article><h2>적용 규칙</h2><p>흑 선공. 가로·세로·대각선으로 같은 돌을 5개 이상 연속 배치하면 승리합니다. 삼삼·사사·장목 금수는 적용하지 않습니다.</p></article></div>}
